name: calendar_app
description: A calendar app for college.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino:
  get_storage:
  get:
  flutter_local_notifications: ^10.0.0
  firebase_core: ^2.24.2
  # flutter_native_timezone: ^1.1.0
  table_calendar: ^3.0.0
  cloud_firestore: ^4.13.5
  firebase_auth:
  # shared_preferences: ^2.0.9
  # device_calendar: ^4.0.0

  # url_launcher: ^6.0.6
  # # device_calendar: ^4.3.1
  # shared_preferences: ^2.2.1

  # cupertino_icons: ^1.0.2

  # add_2_calendar: ^2.1.2

  # firebase_core: ^1.10.0
  # cloud_firestore: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/Logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
