// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmbtKUbHsUydXnjZacmAopz0wzNXqUzWw',
    appId: '1:898688418990:web:9d018f7f18292ba154593f',
    messagingSenderId: '898688418990',
    projectId: 'calendar-app-asiet',
    authDomain: 'calendar-app-asiet.firebaseapp.com',
    storageBucket: 'calendar-app-asiet.appspot.com',
    measurementId: 'G-6QS3CLBRPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWBYY9jRmE53KDIPyJ24eT0BLdoXF2gk',
    appId: '1:898688418990:android:6d9c7cd0ccfa264c54593f',
    messagingSenderId: '898688418990',
    projectId: 'calendar-app-asiet',
    storageBucket: 'calendar-app-asiet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQKdC5_yt1jJeu0VF144vNPI0cvVSG8mM',
    appId: '1:898688418990:ios:2c0d145622f64f8254593f',
    messagingSenderId: '898688418990',
    projectId: 'calendar-app-asiet',
    storageBucket: 'calendar-app-asiet.appspot.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQKdC5_yt1jJeu0VF144vNPI0cvVSG8mM',
    appId: '1:898688418990:ios:a15dfa9dd7a1258154593f',
    messagingSenderId: '898688418990',
    projectId: 'calendar-app-asiet',
    storageBucket: 'calendar-app-asiet.appspot.com',
    iosBundleId: 'com.example.calendarApp.RunnerTests',
  );
}
